image: stage1/symfony2

options:
    front_controller: app.php

env:
  SYMFONY_ENV: prod

urls:
  - foo
  - bar

build:
  - composer self-update
  - composer install --ansi --no-dev --no-interaction --prefer-dist --no-progress