# Oldsound RabbitMQ Bundle
old_sound_rabbit_mq:
    connections:
        default:
            host:      %rabbitmq_host%
            port:      5672
            user:      %rabbitmq_user%
            password:  %rabbitmq_password%
            vhost:     %rabbitmq_vhost%
            lazy:      true
    producers:
        build:
            connection: default
            exchange_options: { name: 'build', type: direct }
        kill:
            connection: default
            exchange_options: { name: 'kill', type: direct }
        project_import:
            connection: default
            exchange_options: { name: 'project_import', type: direct }
        websocket:
            connection: default
            exchange_options: { name: 'websockets', type: direct, auto_delete: true, durable: false }
    consumers:
        build:
            connection: default
            exchange_options: { name: 'build', type: direct }
            queue_options:    { name: 'build' }
            callback:         app_core.consumer.build
            qos_options:      { prefetch_count: 1 }
        kill:
            connection: default
            exchange_options: { name: 'kill', type: direct }
            queue_options:    { name: 'kill' }
            callback:         app_core.consumer.kill
            qos_options:      { prefetch_count: 1 }
        project_import:
            connection: default
            exchange_options: { name: 'project_import', type: direct }
            queue_options:    { name: 'project_import' }
            callback:         app_core.consumer.project_import
        docker_output:
            connection: default
            exchange_options: { name: 'aldis', type: fanout, auto_delete: true, durable: false }
            queue_options:    { name: 'docker_output' }
            callback:         app_core.consumer.docker_output