# Oldsound RabbitMQ Bundle
old_sound_rabbit_mq:
    connections:
        default:
            host:      'localhost'
            port:      5672
            user:      'guest'
            password:  'guest'
            vhost:     '/'
    producers:
        build:
            connection: default
            exchange_options: { name: 'build', type: direct }
        kill:
            connection: default
            exchange_options: { name: 'kill', type: direct }
        project_import:
            connection: default
            exchange_options: { name: 'project_import', type: direct }
        websocket:
            connection: default
            exchange_options: { name: 'amq.fanout', type: fanout }
    consumers:
        build:
            connection: default
            exchange_options: { name: 'build', type: direct }
            queue_options:    { name: 'build' }
            callback:         app_core.consumer.build
        kill:
            connection: default
            exchange_options: { name: 'kill', type: direct }
            queue_options:    { name: 'kill' }
            callback:         app_core.consumer.kill
        project_import:
            connection: default
            exchange_options: { name: 'project_import', type: direct }
            queue_options:    { name: 'project_import' }
            callback:         app_core.consumer.project_import
        docker_output:
            connection: default
            exchange_options: { name: 'docker_output', type: direct }
            queue_options:    { name: 'docker_output' }
            callback:         app_core.consumer.docker_output